SELECT C5_NUM AS NUMERO_DO_PEDIDO, C6_PRODUTO AS CODIGO_PRODUTO, C6_DESCRI AS PRODUTO, C6_UNSVEN AS CAIXAS, C6_QTDVEN AS UNIDADES FROM SC5010
INNER JOIN SC6010 ON C5_NUM = C6_NUM
WHERE C5_NUM = '064528'
ORDER BY CODIGO_PRODUTO